FROM node:20.12-alpine AS base

FROM base AS deps

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./ 
COPY tsconfig.base.json ./

# Copy all files for apps
COPY apps/server/package.json apps/server/tsconfig.json ./apps/server/
COPY apps/frontend/package.json apps/frontend/tsconfig.json ./apps/frontend/

# Copy all files for workspace packages
COPY packages/api/package.json packages/api/tsconfig.json ./packages/api/
COPY packages/attempt/package.json packages/attempt/tsconfig.json ./packages/attempt/
COPY packages/db/package.json packages/db/tsconfig.json ./packages/db/
COPY packages/fetcher/package.json packages/fetcher/tsconfig.json ./packages/fetcher/
COPY packages/meter/package.json packages/meter/tsconfig.json ./packages/meter/
COPY packages/riot/package.json packages/riot/tsconfig.json ./packages/riot/
COPY packages/ui/package.json packages/ui/tsconfig.json ./packages/ui/

ENV NODE_ENV=development

RUN npm i -g corepack
RUN corepack enable pnpm
RUN pnpm install

FROM base AS builder

WORKDIR /app

COPY --from=deps ./app .
COPY apps/frontend ./apps/frontend
COPY packages ./packages

WORKDIR /app/apps/frontend

RUN npm i -g corepack
RUN corepack enable pnpm
RUN pnpm install
RUN pnpm run build

FROM base AS runner

WORKDIR /app
COPY --from=deps ./app ./
COPY apps/server ./apps/server
COPY packages ./packages

WORKDIR /app/apps/server
COPY --from=builder ./app/apps/frontend/dist ./dist

RUN npm i -g corepack
RUN corepack enable pnpm
RUN pnpm install
RUN pnpm run build

EXPOSE 3050

CMD ["pnpm", "run", "start"]
