FROM node:20.12-alpine AS base

FROM base AS deps

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
COPY pnpm-workspace.yaml ./

# Copy all package.json files for apps
COPY apps/server/package.json apps/server/yarn.lock* apps/server/package-lock.json* apps/server/pnpm-lock.yaml* apps/server/.npmrc* ./apps/server/
COPY apps/frontend/package.json apps/frontend/yarn.lock* apps/frontend/package-lock.json* apps/frontend/pnpm-lock.yaml* apps/frontend/.npmrc* ./apps/frontend/

# Copy all package.json files for workspace packages
COPY packages/api/package.json ./packages/api/
COPY packages/attempt/package.json ./packages/attempt/
COPY packages/db/package.json ./packages/db/
COPY packages/fetcher/package.json ./packages/fetcher/
COPY packages/riot/package.json ./packages/riot/
COPY packages/sj/package.json ./packages/sj/
COPY packages/ui/package.json ./packages/ui/

# Copy necessary package files for dependencies
COPY packages/db/migrations ./packages/db/migrations

WORKDIR /app

ENV NODE_ENV=development

RUN npm i -g corepack

RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

WORKDIR /app

COPY --from=deps ./app .
COPY apps/frontend ./apps/frontend
COPY packages ./packages

WORKDIR /app/apps/frontend

RUN npm install -g typescript

RUN npm i -g corepack

RUN \
  if [ -f yarn.lock ]; then yarn run build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS runner

WORKDIR /app
COPY --from=deps ./app ./
COPY apps/server ./apps/server
COPY packages ./packages

WORKDIR /app/apps/server
COPY --from=builder ./app/apps/frontend/dist ./dist

RUN corepack enable pnpm
RUN pnpm install
RUN pnpm run build

EXPOSE 3050

CMD ["pnpm", "run", "start"]