name: "Setup Golang and Migrate CLI"
description: "Setup dependencies required to run migration pipelines"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        cache: true

    - name: Install golang-migrate
      shell: bash
      run: |
        go install -tags 'pgx5' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
