name: Deploy Web Service
description: Deploys web service to k8s cluster

inputs:
  ENVIRONMENT:
    description: "'staging' or 'production'"
    required: true
  VERSION:
    description: "For example, '1.2.34' or 'staging-abc3133'"
    required: true

runs:
  using: composite
  steps:
    - name: Deploy web image tag
      shell: bash
      run: bun run .github/scripts/src/deploy --environment "${{ inputs.ENVIRONMENT }}" --type web --newTagVersion "${{ inputs.VERSION }}"
