name: Deploy Web Service
description: Builds web image and deploys to Coolify

inputs:
  DOCKER_HUB_PAT:
    description: Docker Hub personal access token
    required: true
  COOLIFY_PAT:
    description: Coolify personal access token
    required: true
  COOLIFY_UUID:
    description: Coolify service UUID
    required: true
  TAG_PREFIX:
    description: Docker tag prefix (e.g., staging-, empty for prod)
    required: false
    default: ""
  ENV_FILE:
    description: Environment file to use (.env.staging or .env.production)
    required: true

runs:
  using: composite
  steps:
    - name: Build and push web image
      shell: bash
      run: bash .github/scripts/build-image.sh
      env:
        DOCKER_HUB_PAT: ${{ inputs.DOCKER_HUB_PAT }}
        TYPE: web
        DOCKER_UPLOAD: true
        TAG_PREFIX: ${{ inputs.TAG_PREFIX }}
        DOCKER_FILE_NAME: Dockerfile.web

    - name: Update Coolify Environment Variables
      shell: bash
      run: bash .github/scripts/update-coolify-env.sh ${{ inputs.ENV_FILE }} ${{ inputs.COOLIFY_UUID }}
      env:
        COOLIFY_PAT: ${{ inputs.COOLIFY_PAT }}

    - name: Trigger Coolify Redeploy
      shell: bash
      run: |
        RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" \
        -X POST \
        -H "Authorization: Bearer ${{ inputs.COOLIFY_PAT }}" \
        -H "Content-Type: application/json" \
        https://coolify.tahmid.io/api/v1/deploy?uuid=${{ inputs.COOLIFY_UUID }})

        HTTP_BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS:.*//g')
        HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

        echo "$HTTP_STATUS"

        if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 300 ]; then
            exit 1
        fi

        DEPLOYMENT_ID=$(echo "$HTTP_BODY" | jq -r '.deployments[0].deployment_uuid')

        echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_ENV

    - name: Poll Deployment Status
      shell: bash
      run: |
        DEPLOYMENT_ID="${{ env.deployment_id }}"

         if [ -z "$DEPLOYMENT_ID" ]; then
             echo "Deployment ID is empty."
             exit 1
         fi

        echo "Waiting for deployment to be promoted."

        for i in {1..60}; do
            RESPONSE=$(curl -s -X GET \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer ${{ inputs.COOLIFY_PAT }}" \
                "https://coolify.tahmid.io/api/v1/deployments/$DEPLOYMENT_ID")

            PHASE=$(echo "$RESPONSE" | jq -r '.status')

            echo "Deployment phase: $PHASE"

            if [ "$PHASE" == "finished" ]; then
                echo "Deployment is active."
                exit 0
            elif [ "$PHASE" == "failed" ] || [ "$PHASE" == "error" ] || [ "$PHASE" == "canceled" ]; then
                echo "Deployment failed with phase: $PHASE"
                exit 1
            fi

            echo "Waiting for deployment to complete, sleep 10... ($i/60)"
            sleep 10
        done

        echo "Deployment did not reach a valid state within 10 minutes."
        exit 1
