import type { PlayerData } from "../../../autogenerated";

type Puuid = string;

export const GET_PLAYER_BY_PUUID_DATA: Record<Puuid, PlayerData> = {
  "ed62b133-a56a-5f5c-a704-7beb5da23e98": {
    DisplayName: "",
    Subject: "ed62b133-a56a-5f5c-a704-7beb5da23e98",
    GameName: "1ef55c0946fe6e",
    TagLine: "1ef55",
  },
  "4f8b2c1d-9a3e-5b7f-8c4d-2e6a1b9d3c5e": {
    DisplayName: "",
    Subject: "4f8b2c1d-9a3e-5b7f-8c4d-2e6a1b9d3c5e",
    GameName: "secondaryacceptanceuser",
    TagLine: "scnd1",
  },
};
