name: Build & Deploy Cron Service
description: Builds cron image and deploys to Coolify

inputs:
  ENVIRONMENT:
    description: "'staging' or 'production'"
    required: true

runs:
  using: composite
  steps:
    - name: Build and push cron image
      shell: bash
      id: build-image
      run: bun run .github/scripts/src/build-image --environment "${{ inputs.ENVIRONMENT }}" --dockerUpload --type cron --dockerFileName Dockerfile.scripts --getGhaOutput=true

    - name: Deploy cron image tag
      shell: bash
      run: bun run .github/scripts/src/deploy --environment "${{ inputs.ENVIRONMENT }}" --type cron --newTagVersion "${{ steps.build-image.outputs.tag }}"
