import type { RiotMatchInfoType } from "../../../autogenerated";

type Puuid = string;

export const GET_COMPETITIVE_UPDATES_DATA: Record<Puuid, RiotMatchInfoType> = {
  "ed62b133-a56a-5f5c-a704-7beb5da23e98": {
    Version: 0,
    Subject: "ed62b133-a56a-5f5c-a704-7beb5da23e98",
    httpStatus: 200,
    errorCode: undefined,
    Matches: [
      {
        MatchID: "2113ca91-542d-4099-bf08-4390b4200de7",
        MapID: "/Game/Maps/Pitt/Pitt",
        SeasonID: "9d85c932-4820-c060-09c3-668636d4df1b",
        MatchStartTime: 1776630091030,
        TierAfterUpdate: 0,
        TierBeforeUpdate: 0,
        RankedRatingAfterUpdate: 0,
        RankedRatingBeforeUpdate: 0,
        RankedRatingEarned: 0,
        RankedRatingPerformanceBonus: 0,
        CompetitiveMovement: "MOVEMENT_UNKNOWN",
        AFKPenalty: 0,
      },
    ],
  },
  "4f8b2c1d-9a3e-5b7f-8c4d-2e6a1b9d3c5e": {
    Version: 0,
    Subject: "4f8b2c1d-9a3e-5b7f-8c4d-2e6a1b9d3c5e",
    httpStatus: 200,
    errorCode: undefined,
    Matches: [
      {
        MatchID: "7d9e3a1b-2c4f-4d8b-9e1c-3f5a7b6d4e2c",
        MapID: "/Game/Maps/Pitt/Pitt",
        SeasonID: "9d85c932-4820-c060-09c3-668636d4df1b",
        MatchStartTime: 1776630091030,
        TierAfterUpdate: 21,
        TierBeforeUpdate: 21,
        RankedRatingAfterUpdate: 42,
        RankedRatingBeforeUpdate: 30,
        RankedRatingEarned: 12,
        RankedRatingPerformanceBonus: 0,
        CompetitiveMovement: "MOVEMENT_UNKNOWN",
        AFKPenalty: 0,
      },
    ],
  },
};
