"""Added entitlement and auth to db

Revision ID: 6315d7046282
Revises: 18f7720f9a20
Create Date: 2024-04-29 19:05:30.264618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6315d7046282'
down_revision = '18f7720f9a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entitlement', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('auth', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auth')
        batch_op.drop_column('entitlement')

    # ### end Alembic commands ###
