// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function CheckAuthentication() {
  return window['go']['main']['App']['CheckAuthentication']();
}

export function GetPlayerInfo() {
  return window['go']['main']['App']['GetPlayerInfo']();
}

export function GetRiotMatchInfo(arg1) {
  return window['go']['main']['App']['GetRiotMatchInfo'](arg1);
}

export function GetShallowMatches() {
  return window['go']['main']['App']['GetShallowMatches']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Unauthenticate() {
  return window['go']['main']['App']['Unauthenticate']();
}
