// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authenticate(arg1:main.AuthenticatePayload):Promise<main.Response>;

export function CheckAuthentication():Promise<main.Response>;

export function FindName(arg1:main.FindNamePayload):Promise<main.Response>;

export function FindRank(arg1:main.FindRankPayload):Promise<main.Response>;

export function GetPlayerInfo():Promise<main.Response>;

export function GetRiotMatchInfo(arg1:string):Promise<main.Response>;

export function GetShallowMatches():Promise<main.Response>;

export function Greet(arg1:string):Promise<string>;

export function Unauthenticate():Promise<main.Response>;
