import type { Impl, IRiotClient } from "./types";

import { RiotClientImpl } from "./impl";
import { MockRiotClient } from "./mock";

// Hoist the exported types out under the same namespace.
export * from "./autogenerated";

export let RiotClient: IRiotClient = RiotClientImpl;

/**
 * Call this as early as you possibly can within your application.
 */
export function changeRiotClientImpl(impl: Impl): void {
  if (impl === "real") {
    RiotClient = RiotClientImpl;
  } else {
    RiotClient = new MockRiotClient(impl);
  }
}
